import { siteContent } from "./data/content.js";
import { products } from "./data/products.js";
const esc=value=>String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]));
function media(work,index){if(!work.media?.sources?.length)return `<div class="media-placeholder ${work.orientation||"landscape"}"><span>${esc(work.placeholder)}</span><small>${esc(work.preferredMedia)}</small></div>`;const sources=work.media.sources.map(source=>`<source src="${esc(source.src)}" type="${esc(source.type)}">`).join("");return `<div class="work-media ${work.orientation||"landscape"}"><video ${index===0?'preload="metadata"':'preload="none"'} ${work.poster?`poster="${esc(work.poster)}"`:""} muted loop playsinline data-autoplay>${sources}</video><button class="sound-toggle" type="button">SOUND OFF</button></div>`}
document.querySelector("#featured-work").innerHTML=siteContent.featuredWorks.map((work,index)=>`<article class="featured-work section-rule reveal"><div class="work-label"><b>FEATURED / ${String(index+1).padStart(3,"0")}</b><span>${esc(work.title)}</span></div>${media(work,index)}<div class="work-meta"><span>${esc(work.type)} / ${esc(work.year)}</span>${work.toolsUsed?.length?`<p>MADE WITH ${work.toolsUsed.join(" / ")}</p>`:""}</div></article>`).join("");
const details=new Set(["timefield","avm"]);document.querySelector("#tool-preview").innerHTML=products.filter(product=>product.homePreview).slice(0,3).map((product,index)=>{const href=details.has(product.slug)?`./products/${product.slug}/`:"./tools/";return `<article class="product-card reveal"><div class="product-heading"><h3>${esc(product.name)}</h3></div><a class="product-image" href="${href}"><img loading="lazy" src="./${esc(product.image)}" alt="${esc(product.name)} interface"><span class="index">0${index+1}</span></a><div class="product-info"><p>${esc(product.category)}</p><span class="technical">${esc(product.exhibitNotes)}</span><a class="view-link" href="${href}">VIEW →</a></div></article>`}).join("");
document.querySelector("#social-links").innerHTML=siteContent.socials.map(social=>social.url?`<a href="${esc(social.url)}" target="_blank" rel="noreferrer">${esc(social.label)} ↗</a>`:`<span>${esc(social.label)} <small>[ URL NEEDED ]</small></span>`).join("");document.querySelector("#year").textContent=new Date().getFullYear();
const toggle=document.querySelector(".nav-toggle");toggle.addEventListener("click",()=>{const open=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!open));document.querySelector("#nav").classList.toggle("open",!open)});
const reduced=matchMedia("(prefers-reduced-motion: reduce)");const videos=new IntersectionObserver(entries=>entries.forEach(entry=>{const video=entry.target;if(entry.isIntersecting&&!reduced.matches)video.play().catch(()=>video.controls=true);else video.pause()}),{threshold:.55});document.querySelectorAll("video[data-autoplay]").forEach(video=>videos.observe(video));document.addEventListener("click",event=>{const button=event.target.closest(".sound-toggle");if(!button)return;const video=button.parentElement.querySelector("video");video.muted=!video.muted;button.textContent=video.muted?"SOUND OFF":"SOUND ON"});const reveals=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add("visible")),{threshold:.08});document.querySelectorAll(".reveal").forEach(element=>reveals.observe(element));
